'use client';
/* eslint-disable @next/next/no-img-element -- Embedded user icons are already local and need no optimizer. */
import {useState} from 'react';
import {defaultDockLaunch,type DockLaunch} from '@/lib/dock-launch';
import type {MockupMotionFragment} from '@/lib/mockup-motion';
export function DockLaunchControls({fragment,onUpdate}:{fragment:MockupMotionFragment;onUpdate:(v:Partial<MockupMotionFragment>)=>void}){
 const [error,setError]=useState('');const d=fragment.dockLaunch;
 if(!d)return <button className="border rounded p-2 m-3" onClick={()=>onUpdate({dockLaunch:defaultDockLaunch()})}>Add Dock launch</button>;
 const update=(v:Partial<DockLaunch>)=>onUpdate({dockLaunch:{...d,...v}});
 return <section aria-label="Dock launch settings" className="p-3 space-y-3 border-t"><h3>Dock launch</h3><label className="flex gap-2"><input type="checkbox" checked={d.enabled} onChange={e=>update({enabled:e.target.checked})}/>Enabled</label>
 <label className="flex gap-2 text-xs"><input type="checkbox" checked={d.startFromCenter??false} onChange={e=>update({startFromCenter:e.target.checked,...(e.target.checked&&d.settleDuration===undefined?{settleDuration:.15}:{})})}/>Start Dock in center</label>
 {d.startFromCenter&&<p className="text-xs text-muted-foreground">Dock moves to its desktop position while bouncing. The opening camera settles with it; the window opens after the landing pause.</p>}
 <label className="flex gap-2 text-xs"><input type="checkbox" checked={d.exitAfterOpen??false} onChange={e=>update({exitAfterOpen:e.target.checked,...(e.target.checked?{keepVisible:true}:{})})}/>Slide Dock out after window opens</label>
 <label className="flex gap-2 text-xs"><input type="checkbox" checked={d.followCamera??false} onChange={e=>update({followCamera:e.target.checked,...(e.target.checked?{pinToBottom:false}:{})})}/>Follow desktop camera</label>
 <label className="flex gap-2 text-xs"><input type="checkbox" checked={d.pinToBottom??false} onChange={e=>update({pinToBottom:e.target.checked,...(e.target.checked?{followCamera:false}:{})})}/>Pin Dock to screen bottom</label>
 <label className="flex justify-between text-xs">Appearance<select aria-label="Dock appearance" value={d.appearance??'light'} onChange={e=>update({appearance:e.target.value as 'light'|'dark'})}><option value="dark">macOS dark glass</option><option value="light">Light glass</option></select></label>
 <label className="flex gap-2 text-xs"><input type="checkbox" checked={d.runningDots??false} onChange={e=>update({runningDots:e.target.checked})}/>Running indicators</label>
 {d.icons.length>1&&<label className="flex justify-between text-xs">Icons before divider (0=none)<input aria-label="Icons before divider" className="w-20 bg-background border rounded" type="number" min="0" max={d.icons.length-1} value={d.separatorAfter??0} onChange={e=>{const n=e.target.valueAsNumber;if(Number.isInteger(n)&&n>=0&&n<d.icons.length)update({separatorAfter:n});}}/></label>}
 <label className="block text-xs">Add icons (PNG, JPEG, WebP)<input aria-label="Dock icon upload" type="file" accept="image/png,image/jpeg,image/webp" multiple onChange={async e=>{try{const files=Array.from(e.target.files??[]);if(files.length+d.icons.length>8)throw new Error('Maximum 8 icons');const added=await Promise.all(files.map(file=>new Promise<string>((resolve,reject)=>{if(file.size>1000000)return reject(new Error('Each icon must be under 1 MB'));const r=new FileReader();r.onload=()=>resolve(String(r.result));r.onerror=()=>reject(new Error('Cannot read icon'));r.readAsDataURL(file);})));update({icons:[...d.icons,...added]});setError('');}catch(err){setError(String(err));}e.target.value='';}}/></label>
 {error&&<p role="alert">{error}</p>}<div className="flex gap-2">{d.icons.map((src,i)=><button key={i} aria-label={`Launch icon ${i+1}`} aria-pressed={i===d.selected} className={i===d.selected?'border-2 border-blue-500':'border'} onClick={()=>update({selected:i})}><img src={src} alt="" width={36} height={36}/></button>)}</div>
 {!!d.icons.length&&<button onClick={()=>update({icons:[],selected:0,separatorAfter:0})}>Clear icons</button>}
 {([['glassBlur','Glass blur (px)',0,40,1],['cornerRadius','Dock corner radius (%)',10,45,1],['cameraZoom','Opening camera zoom',1,3,.05],['x','Horizontal position (%)',5,95,1],['y','Vertical position (%)',10,90,1],['size','Icon size (% of height)',3,16,.5],['gap','Icon spacing (%)',0,80,1],['opacity','Glass tint (%)',0,100,1],['start','Bounce start (s)',-3600,60,.05],['bounces','Bounce count',1,4,1],['amplitude','Bounce height (%)',0,100,1],['bounceDuration','Bounce duration (s)',.3,4,.05],['settleDuration','Landing pause (s)',0,1,.05],['exitDelay','Hold after window opens (s)',0,5,.05],['exitDuration','Dock slide-out duration (s)',.15,2,.05],['expandDuration','Expand duration (s)',.25,3,.05]] as const).map(([key,label,min,max,step])=><label key={key} className="flex justify-between items-center gap-2 text-xs">{label}<input className="w-20 border rounded p-1 bg-background" aria-label={label} disabled={key==='y'&&(d.pinToBottom||d.followCamera)} type="number" min={min} max={max} step={step} value={d[key]??({glassBlur:18,cornerRadius:28,cameraZoom:1,settleDuration:d.startFromCenter?.15:0,exitDelay:.5,exitDuration:.45} as Record<string,number>)[key]} onChange={e=>{const n=e.target.valueAsNumber;if(Number.isFinite(n)&&n>=min&&n<=max)update({[key]:key==='bounces'?Math.round(n):n});}}/></label>)}
 <label className="flex gap-2 text-xs"><input type="checkbox" checked={d.keepVisible} disabled={d.exitAfterOpen} onChange={e=>update({keepVisible:e.target.checked})}/>Keep Dock after launch</label><button onClick={()=>onUpdate({dockLaunch:undefined})}>Remove Dock</button></section>;
}
