"use client";
import type { MockupMotionFragment } from '@/lib/mockup-motion';
import type { PointerTrack, PointerEvent, PointerEffect } from '@/lib/pointer-track';

const effects: [PointerEffect,string][]=[['none','None'],['press','Soft press'],['ripple','Ripple'],['halo','Halo'],['distort','Elastic distortion']];
export const defaultPointerTrack = ():PointerTrack=>({enabled:true,size:28,effect:'press',radius:.12,strength:.45,duration:.36,fps:60,events:[{id:crypto.randomUUID(),time:0,x:.5,y:.8,kind:'move',travel:.4}]});
function NumberInput({label,value,min,max,step=.01,onCommit}:{label:string;value:number;min:number;max:number;step?:number;onCommit:(value:number)=>void}) {
 return <label className="flex items-center justify-between gap-2 text-xs">{label}<input key={`${label}:${value}`} aria-label={label} type="number" min={min} max={max} step={step} defaultValue={Number(value.toFixed(4))} className="w-24 rounded border border-border bg-background p-2" onKeyDown={e=>{if(e.key==='Enter')e.currentTarget.blur();if(e.key==='Escape'){e.currentTarget.value=String(value);e.currentTarget.blur();}}} onBlur={e=>{const n=Number(e.target.value);if(e.target.value!==''&&Number.isFinite(n)&&n>=min&&n<=max)onCommit(n);else e.target.value=String(value);}}/></label>;
}
export function PointerTrackEditor({fragment,onUpdate,onCreate,currentTime=0,onSeek,selectedId,onSelect,thumbnail}:{fragment?:MockupMotionFragment;onUpdate:(patch:Partial<MockupMotionFragment>)=>void;onCreate:()=>void;currentTime?:number;onSeek?:(t:number)=>void;selectedId?:string|null;onSelect?:(id:string|null)=>void;thumbnail?:string|null}) {
 if(!fragment)return <div className="p-4 space-y-4"><h2>Mouse animation</h2><p className="text-xs text-muted-foreground">Add an editable mouse track to your video.</p><button className="rounded border p-3 text-sm" onClick={onCreate}>Create mouse track</button></div>;
 const track=fragment.pointerTrack;
 if(!track)return <div className="p-4 space-y-4"><h2>Mouse animation</h2><p className="text-xs text-muted-foreground">Use footage without an existing cursor to avoid duplicates.</p><button className="rounded border p-3 text-sm" onClick={()=>onUpdate({pointerTrack:defaultPointerTrack()})}>Add mouse animation</button></div>;
 const update=(patch:Partial<PointerTrack>)=>onUpdate({pointerTrack:{...track,...patch}});
 const event=track.events.find(e=>e.id===selectedId)??track.events[0];
 const select=(e:PointerEvent)=>{onSelect?.(e.id);onSeek?.(Math.max(fragment.startTime,Math.min(fragment.endTime,fragment.startTime+e.time)));};
 const changeEvent=(patch:Partial<PointerEvent>)=>{if(!event)return;const next={...event,...patch};update({events:track.events.map(e=>e.id===event.id?next:e).sort((a,b)=>a.time-b.time)});onSeek?.(Math.max(fragment.startTime,Math.min(fragment.endTime,fragment.startTime+next.time)));};
 const add=(kind:'move'|'click')=>{const t=Math.max(0,Math.min(fragment.endTime-fragment.startTime,currentTime-fragment.startTime));const e:PointerEvent={id:crypto.randomUUID(),time:t,x:event?.x??.5,y:event?.y??.5,kind,travel:.4};update({events:[...track.events,e].sort((a,b)=>a.time-b.time)});onSelect?.(e.id);};
 return <div className="h-full overflow-y-auto p-4 space-y-4 text-foreground">
  <label className="flex justify-between text-sm font-medium">Mouse animation<input type="checkbox" checked={track.enabled} onChange={e=>update({enabled:e.target.checked})}/></label>
  <p className="text-xs text-muted-foreground">Mouse and clicks are editable project events. Select an event in this panel or the Mouse timeline.</p>
  <NumberInput label="Cursor size (px)" value={track.size} min={1} max={256} step={1} onCommit={size=>update({size})}/>
  <label className="flex justify-between text-xs items-center">Frame rate<select aria-label="Mouse frame rate" value={track.fps??60} className="rounded border bg-background p-2" onChange={e=>update({fps:Number(e.target.value) as 30|60})}><option value={60}>60 fps</option><option value={30}>30 fps</option></select></label>
  <section className="space-y-3 rounded border border-border p-3"><h3 className="text-xs font-medium">Default click effect</h3><div className="grid grid-cols-2 gap-2">{effects.map(([id,label])=><button key={id} aria-pressed={track.effect===id} className={`rounded border p-2 text-xs ${track.effect===id?'border-violet-500 bg-violet-500/10':'border-border'}`} onClick={()=>update({effect:id})}>{label}</button>)}</div>
  <NumberInput label="Effect radius (%)" value={track.radius*100} min={0} max={100} step={1} onCommit={v=>update({radius:v/100})}/><NumberInput label="Effect strength (%)" value={track.strength*100} min={0} max={100} step={1} onCommit={v=>update({strength:v/100})}/><NumberInput label="Effect duration (s)" value={track.duration} min={.01} max={10} step={.05} onCommit={duration=>update({duration})}/>
  </section>
  <div className="flex gap-2"><button disabled={track.events.length>=200} className="flex-1 rounded border p-2 text-xs" onClick={()=>add('move')}>Add move</button><button disabled={track.events.length>=200} className="flex-1 rounded border p-2 text-xs" onClick={()=>add('click')}>Add click</button></div>
  <div className="grid grid-cols-2 gap-2" aria-label="Pointer events">{track.events.map(e=><button key={e.id} aria-pressed={event?.id===e.id} className={`rounded border p-2 text-xs ${event?.id===e.id?'border-violet-500':'border-border'}`} onClick={()=>select(e)}>{e.kind==='click'?'Click':'Move'} · {e.time.toFixed(2)}s</button>)}</div>
  {event&&<section className="space-y-3 rounded border border-border p-3"><h3 className="text-xs font-medium">Selected mouse event</h3>
   <NumberInput label="Event time (s)" value={event.time} min={Math.min(0,event.time)} max={Math.max(event.time,fragment.endTime-fragment.startTime)} onCommit={time=>changeEvent({time})}/>
   <div role="button" tabIndex={0} aria-label="Mouse position" className="relative aspect-video overflow-hidden rounded border bg-muted cursor-crosshair touch-none" style={thumbnail?{backgroundImage:`url(${thumbnail})`,backgroundSize:'100% 100%'}:undefined} onPointerDown={e=>{e.currentTarget.setPointerCapture(e.pointerId);const r=e.currentTarget.getBoundingClientRect();changeEvent({x:Math.max(0,Math.min(1,(e.clientX-r.left)/r.width)),y:Math.max(0,Math.min(1,(e.clientY-r.top)/r.height))});}} onPointerMove={e=>{if(!e.currentTarget.hasPointerCapture(e.pointerId))return;const r=e.currentTarget.getBoundingClientRect();changeEvent({x:Math.max(0,Math.min(1,(e.clientX-r.left)/r.width)),y:Math.max(0,Math.min(1,(e.clientY-r.top)/r.height))});}} onKeyDown={e=>{const moves:Record<string,[number,number]>={ArrowLeft:[-.01,0],ArrowRight:[.01,0],ArrowUp:[0,-.01],ArrowDown:[0,.01]};if(moves[e.key]){e.preventDefault();changeEvent({x:Math.max(0,Math.min(1,event.x+moves[e.key][0])),y:Math.max(0,Math.min(1,event.y+moves[e.key][1]))});}}}><span className="pointer-events-none absolute size-3 -translate-x-1/2 -translate-y-1/2 rounded-full border-2 border-violet-600 bg-white" style={{left:`${event.x*100}%`,top:`${event.y*100}%`}}/></div>
   <NumberInput label="Mouse X (%)" value={event.x*100} min={0} max={100} onCommit={x=>changeEvent({x:x/100})}/><NumberInput label="Mouse Y (%)" value={event.y*100} min={0} max={100} onCommit={y=>changeEvent({y:y/100})}/><NumberInput label="Travel time (s)" value={event.travel??Math.max(.01,event.time-(track.events[track.events.indexOf(event)-1]?.time??event.time-.4))} min={0} max={3600} onCommit={travel=>changeEvent({travel})}/>
   {event.kind==='click'&&<><label className="flex justify-between items-center text-xs">Click effect<select aria-label="Event click effect" value={event.effect??'inherit'} className="max-w-40 rounded border bg-background p-2" onChange={e=>changeEvent({effect:e.target.value==='inherit'?undefined:e.target.value as PointerEffect})}><option value="inherit">Use default</option>{effects.map(([id,label])=><option key={id} value={id}>{label}</option>)}</select></label><button className="w-full rounded border border-violet-400 p-2 text-xs" onClick={()=>{onSeek?.(Math.max(fragment.startTime,Math.min(fragment.endTime,fragment.startTime+event.time+track.duration*.3)));}}>Preview click peak</button></>}
   <button disabled={track.events.length<=1} className="text-xs text-destructive disabled:opacity-40" onClick={()=>{update({events:track.events.filter(e=>e.id!==event.id)});onSelect?.(null);}}>Delete event</button>
  </section>}
 </div>;
}
